triage:
  label: triage
  removeLabelWhenProjectAssigned: true
  dryRun: false
  
closeAndLock:
  labels:
    - label: incomplete
      message: >
        Thanks for the issue! It appears that you have not filled out the provided issue template. We use this issue
        template in order to gather more information and further assist you. Please create a new issue and ensure the
        template is fully filled out.
    
    
        Thank you for using Ionic!
    - label: "bot: support"
      message: >
        We use the issue tracker exclusively for bug reports and feature requests.
        However, this issue appears to be a support request. Please use our
        [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/)
        channels to get help with your question.


        Thanks for using Ionic!
  close: true
  lock: true
  dryRun: false
  
labelPullRequest:
  labels:
    - label: "bot: master-code"
      branch: master
    - label: "bot: legacy-code"
      branch: legacy
    - label: "bot: about-module"
      path: .*/about/
    - label: "bot: home-module"
      branch: master
      path: ^src/app/home
    - label: "bot: config"
      branch: master
      path: package.json
    - label: "bot: config"
      branch: master
      path: config.xml
  dryRun: false

stale:
  days: 3
  maxIssuesPerRun: 42
  exemptLabels:
    - good first issue
    - triage
  exemptProjects: true
  exemptMilestones: true
  label: wontfix
  close: true
  lock: true
  dryRun: false
  
noReply:
  days: 1
  maxIssuesPerRun: 100
  label: needs reply
  responseLabel: triage
  exemptProjects: true
  exemptMilestones: true
  message: >
    Thanks for the issue! Some nice thing about ppl not responding here.

    Thank you for using Ionic!
  close: true
  lock: true
  dryRun: false

lockClosed:
  days: 30
  maxIssuesPerRun: 100
  message: >
    This issue has been closed for a while now and is now locked to further comment.  If this is still
    an issue with the latest version of Ionic, please create a new issue and ensure the
    template is fully filled out.

    Thank you for using Ionic!
  dryRun: false
  
wrongRepo:
  repos:
    - label: fred
      repo: cli
      message: >
        This is a test message.


        Thank-you
    - label: moveit
      repo: test-bot-target
      message: >
        Yo Yo Yo!! Thanks for the issue, but this is the wrong repo. I will move it for you.


        You're welcome
    - label: barney
      repo: stencil
      message: >
        This is another test message.


        Thank-you
  close: true
  lock: true
  dryRun: false
  
