triage:
  label: triage
  removeLabelWhenProjectAssigned: false
  dryRun: false
  
closeAndLock:
  labels:
    - label: incomplete
      message: >
        Thanks for the issue! It appears that you have not filled out the provided issue template. We use this issue
        template in order to gather more information and further assist you. Please create a new issue and ensure the
        template is fully filled out.
    
    
        Thank you for using Ionic!
    - label: "bot: support"
      message: >
        We use the issue tracker exclusively for bug reports and feature requests.
        However, this issue appears to be a support request. Please use our
        [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/)
        channels to get help with your question.


        Thanks for using Ionic!
  close: true
  lock: true
  dryRun: false
  
stale:
  days: 1
  maxIssuesPerRun: 42
  exemptLabels:
    - good first issue
    - triage
  exemptProjects: true
  exemptMilestones: true
  label: wontfix
  message: >
    This issue is being closed due to lack of inactivity. This could mean that it has been fixed or it
    could mean that the bandwidth does not currently exist in order to fix it.
  close: true
  lock: true
  dryRun: false

wrongRepo:
  repos:
    - label: fred
      repo: cli
      message: >
        This is a test message.


        Thank-you
    - label: moveit
      repo: test-bot-target
      message: >
        Yo Yo Yo!! Thanks for the issue, but this is the wrong repo. I will move it for you.


        You're welcome
    - label: barney
      repo: stencil
      message: >
        This is another test message.


        Thank-you
  close: true
  lock: true
  dryRun: false
  
