triage:
  label: triage
  dryRun: false

support:
  label: support
  message: >
    We use the issue tracker exclusively for bug reports and feature requests.
    However, this issue appears to be a support request. Please use our
    support channels to get help with the project.
  close: true
  lock: true
  dryRun: false
